### ISSUE TITLE
Change demo xml

### ISSUE THREAD

**Issue by iammannan** [hty527/iPlayer#1]
Your demo code was 

    `<com.android.player.media.VideoPlayer
        android:id="@+id/video_player"
        android:layout_width="match_parent"
        android:layout_height="200dp"
        app:initController="true"/>`

But it should be ( player -> iplayer )

    `<com.android.iplayer.media.VideoPlayer
        android:id="@+id/video_player"
        android:layout_width="match_parent"
        android:layout_height="200dp"
        app:initController="true"/>`

**Comment by hty527** [comment]
Thanks so much for your feedback! The doc is already corrected.

**Comment by 173851399** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
