### ISSUE TITLE
标题栏如何在全屏状态下也显示呢

### ISSUE THREAD

**Issue by mos1128** [hty527/iPlayer#13]
感觉这个库应该是无需大幅度自定义UI的情况下上手最简单的了，有两个不理解
看文档写的toolBarView.showMenus(true,true,true);//是否显示投屏\悬浮窗\功能等按钮，仅限竖屏情况下，横屏模式下强制不显示。但是拉伸倍速这些功能全屏不也会用到吗。
另有没有方法可以在SDK提供的标题栏上面额外增加一些自定义按钮呢，譬如截图、下载等

**Comment by hty527** [comment]
你好，收到你的意见反馈！
此SDK致力于简单化视频播放器的使用，感谢你的支持！
1、由于我这边是播放器的基础交互示例，所有没有内置过多的功能按钮，后续可能会在增加更多功能时内置诸如截屏、倍速、拉升等按钮。
2、在应用目前版本上，可以尝试为标题栏添加自定义menu view，用法如下：
            ControlToolBarView toolBarView=new ControlToolBarView(controller.getContext());
            //或者
            //IControllerView controlWidget = mVideoPlayer.getController().findControlWidgetByTag(IVideoController.TARGET_CONTROL_TOOL);
            //if(null!=controlWidget&&controlWidget instanceof ControlToolBarView){
            //    ControlToolBarView toolBarView= (ControlToolBarView) controlWidget;
            //}
            LinearLayout linearLayout = (LinearLayout) toolBarView.findViewById(com.android.iplayer.widget.R.id.controller_menus);
            linearLayout.addView(view,0);//添加你自己的View到标题栏右侧居左的位置

**Comment by mos1128** [comment]
感谢回复
针对回复（1），其实我想表达的是：在横屏状态下，标题栏的功能区（即@+id/controller_menus这个布局）全部被隐藏了，反而是在竖屏状况下显示功能区，这点是否和主流的使用方式有点相反了。
回复（2）提到的方法我通过尝试过，在已有标题栏上扩展确实能在代码量较少的情况下实现功能，而不需要整个重写ControlUI，也方便后续更新。但是因为（1）的问题，如果不重写player_control_toolar.xml的话，还是会在全屏时隐藏我增加的功能项。
目前的思路是在标题栏的根布局上仿写功能区的布局再addView进去，还未进行尝试。
另：确实是非常好用的库

**Comment by hty527** [comment]
晚上好！
1、的确是相反了，计划在后续版本拓展更多功能时一起重构横屏菜单栏。
2、针对第2个建议仿写ControlToolBarView自定义自己的标题栏，可以在最小改动下实现自己的UI和功能拓展。
