### ISSUE TITLE
赞！有几点小建议

### ISSUE THREAD

**Issue by wushaoge** [hty527/iPlayer#15]
我目前用的gsy，看了iplayer感觉很不错，无缝转场、全局悬浮、预缓存都比gsy强。不过有几点小建议
1、文档说明增加exo版本号说明
2、BasePlayer关于生命周期的控制可以用Lifecycle，目前有很多都是在baseActivity实现
3、demo中悬浮窗在手指拖动的第一时间位置会往下跳动，悬浮窗功能没必要内置在BasePlayer。悬浮窗不属于播放器的功能，只需提供demo。悬浮窗的适配也会占用大量的精力。
4、横竖屏UI布局  gsy是提供了两套布局
5、对于自定义布局  各种ControlView 感觉不太直观
感觉开源这么好的框架👍

**Comment by 173851399** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by hty527** [comment]
首先感谢对此项目的建言献策！现针对上述5条建议回复如下：
1、当前只在首页有说明exo版本号，接入文档也将同步加入版本号说明。
2、后续版本生命周期考虑使用Lifecycle机制。
3、全局悬浮窗的适配的确非常耗时，当初为了兼容全局窗口和window窗口手势拖动和适配已有机型的不同屏幕相对整个项目开发周期而言适配了较长时间。尽管SDK自带全局悬浮窗能力，但仍然建议接入着使用系统的”画中画“能力。
4、SDK后续版本考虑横竖屏UI独立开来。
5、各种自定义ControlView后续版本持续针对性优化。
