### ISSUE TITLE
竖屏全屏问题

### ISSUE THREAD

**Issue by 173851399** [hty527/iPlayer#2]
请问SDK支持竖屏全屏播放吗？如果不支持的话自定义播放器如何实现？

**Comment by hty527** [comment]
1.SDK暂不支持竖屏全屏播放
2.快速实现竖屏全屏播放器，请继承BasePlayer，参考BasePlayer中的startFullScreen方法代码，理论上在全屏播放时不要调用setRequestedOrientation更改屏幕方向即可。有无其它问题还需要调试。

**Comment by 173851399** [comment]
好的，谢谢！
