### ISSUE TITLE
如何设置竖屏全屏呢？

### ISSUE THREAD

**Issue by casanovawu** [hty527/iPlayer#21]

**Comment by hty527** [comment]
需要更新至2.1.23及以上版本然后按下列步骤api应用竖屏全屏
1、在开启全屏播放之前设置禁止旋转Activity方向，默认开启：mVideoPlayer.shutFullScreenOrientation();
2、mVideoPlayer.startFullScreen();//启动全屏播放，mVideoPlayer.quitFullScreen();//退出全屏播放
