### ISSUE TITLE
一个小问题

### ISSUE THREAD

**Issue by HenryWu01** [hty527/iPlayer#7]
作者您好，我在使用IJK作为播放器时发现了一个问题：如果我不重写AbstractMediaPlayer的话，使用系统的MediaPlayer是可以播放content://开头的路径的。我按照Demo中的自己写了继承AbstractMediaPlayer的IJKMediaPlayer，塞入content://路径后无法播放。我猜应该是IJKMediaPlayer不支持content://的格式？作者有发现这个问题嘛，通过content://反向解析出file://貌似比较困难，能否让ijk直接播放content://路径的视频呢？

**Comment by HenryWu01** [comment]
看到了作者大大六小时前更新的，很奇怪的是系统的MediaPlayer是可以播放content://的，应该是直接读取成iostream读内容了？

**Comment by HenryWu01** [comment]
通过FileOperator获取真实路径解决了

**Comment by hty527** [comment]
不好意思，刚刚看到这条issue。已经解决了就好~
