### ISSUE TITLE
控制台显示I/O error但并没有响应error回调

### ISSUE THREAD

**Issue by sth0409** [hty527/iPlayer#9]
在仿抖音滑动的使用场景中，偶尔会出现无法播放的问题，滑到下个视频再滑回来的时候就能播放了
无法播放时，控制台出现如下日志，显示I/O error但并没有响应error回调

E/IJKMEDIA: error:00000000:lib(0):func(0):reason(0)
I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 2
E/IJKMEDIA: ************************.mp4: I/O error
I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [26394]
I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [26393]
D/IJKMEDIA: ijkmp_shutdown_l()=void
D/IJKMEDIA: ijkmp_dec_ref(): ref=0
D/IJKMEDIA: ijkmp_shutdown_l()
D/IJKMEDIA: ijkmp_shutdown_l()=void
E/IJKMEDIA: SDL_JNI_ThreadDestroyed: [26396] didn't call SDL_JNI_DetachThreadEnv() explicity
I/Pinger: Ping response: `ping ok`, pinged? true
D/PreloadTask: 预缓存成功:position:26,Byte:1056767
D/PreloadTask: 预缓存结束:position:26

**Comment by hty527** [comment]
好的，收到，感谢反馈！我这边检查复现一下。

**Comment by hty527** [comment]
我这边测试机没有复现上述问题，你用的代码版本是多少？是哪些视频资源？

**Comment by sth0409** [comment]
最新版本 2.1.1
我这边是解析的微博视频链接
他这个链接有时效性，我也不确定是不是它视频链接的问题
------------------------------------------视频链接---------
https://f.video.weibocdn.com/o0/XYV0KGBClx07Zn0wsJ1601041200oBTS0E010.mp4?label=mp4_720p&template=1280x720.25.0&ori=0&ps=1CvO5Ia5FwDueA&Expires=1663727943&ssig=HydkkHiF%2F%2B&KID=unistore,video
--------------------------------------------------------------

D/IJKMEDIA: IjkMediaPlayer_setVideoSurface
D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)
D/IJKMEDIA: ffpipeline_set_surface()
D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)=void
D/IJKMEDIA: IjkMediaPlayer_setVideoSurface
D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)
D/IJKMEDIA: ffpipeline_set_surface()
D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)=void
I/GLConsumer: [SurfaceTexture-0-8608-7] detachFromContext
D/IJKMEDIA: IjkMediaPlayer_release
D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)
D/IJKMEDIA: ffpipeline_set_surface()
D/IJKMEDIA: ijkmp_set_android_surface(surface=0x0)=void
D/IJKMEDIA: ijkmp_shutdown_l()
D/IJKMEDIA: message_loop exit
I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [9262]
I/BufferQueueConsumer: [SurfaceTexture-0-8608-7](this:0x74059fd800,id:7,api:0,p:-1,c:-1) disconnect(C)
D/BasePlayer: onPlayerState-->state:STATE_RESET,message:结束播放并重置
D/ShortControllerControl:  
    │ args[0] = BaseController
    │ args[1] = onState-->state:STATE_RESET

D/ShortControllerControl:  
    │ args[0] = ShortControllerControl
    │ args[1] = 0
    │ args[2] = 0
    └──────────────────────────────────────────────────────────────────────────────
    │ args[0] = 
    │ args[1] = onPlayerState-->state:STATE_RESET,message:结束播放并重置,mPosition:7
I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [9263]
E/IJKMEDIA: error:00000000:lib(0):func(0):reason(0)
I/tv.danmaku.ijk.media.player.IjkMediaPlayer: onNativeInvoke 2
E/IJKMEDIA: https://f.video.weibocdn.com/o0/XYV0KGBClx07Zn0wsJ1601041200oBTS0E010.mp4?label=mp4_720p&template=1280x720.25.0&ori=0&ps=1CvO5Ia5FwDueA&Expires=1663727943&ssig=HydkkHiF%2F%2B&KID=unistore,video: I/O error
I/IJKMEDIA: SDL_JNI_DetachThreadEnv: [9264]
D/IJKMEDIA: ijkmp_shutdown_l()=void
D/IJKMEDIA: ijkmp_dec_ref(): ref=0
D/IJKMEDIA: ijkmp_shutdown_l()
D/IJKMEDIA: ijkmp_shutdown_l()=void
E/IJKMEDIA: SDL_JNI_ThreadDestroyed: [9266] didn't call SDL_JNI_DetachThreadEnv() explicity

**Comment by hty527** [comment]
我可能要到国庆节后来针对这个有时效性的链接做调试，可能原因是需要鉴权等。

**Comment by sth0409** [comment]
okok，这两天如果我有时间，我也自查一下我的逻辑

**Comment by sth0409** [comment]
作者你好，我这边发链接放到工程demo里发现没有问题，我自查我的逻辑吧。issue我就先关闭了，如果有问题以后再来和你反馈
